### ISSUE TITLE
[frontend] comment 생성

### ISSUE THREAD

**Issue by sungbin92** [swsnu/swpp2019-team19#100]
목요일까지 해보도록 할게요

**Comment by lightb0x** [comment]
UI 를 바꾸고 있어서 조심하셔야 할 것 같습니다

**Comment by sungbin92** [comment]
전부 component화 하신건 좋은데 component에서 Input을 받는 방법을 잘 모르겠습니다.
그리고 아티클들을 페이지별로 전부 받아오셔서 뿌려주시는 것 같은데 코멘트도 그렇게 해야될 것 같은데 의견좀 부탁드릴게요

**Comment by lightb0x** [comment]
인풋 받는 건 useState 사용해서 받으시면 됩니다.
다만 컴포넌트에서 redux 요청하는 건 아직 잘 모르겠네요 저도 해보고는 있는데

**Comment by ulgal** [comment]
ArticleDetail은 여러 개를 동시에 보여줄 일이 없으니 Container로 바꿔서 comment를 불러오면 될 것 같은데 어떻게 생각하시나요?

**Comment by sungbin92** [comment]
바꿔도 되면 제가 수정하기 편할거같습니다.

**Comment by sungbin92** [comment]
우선 명환님말대로 useState 써서 시도해볼게요

**Comment by ulgal** [comment]
그런데 component에서는 maptoprops등으로 redux에 접근이 불가능한가요? 어떤 부분이 안된다는건지 잘 모르겟어요.

**Comment by lightb0x** [comment]
네 클래스 기반이랑 마찬가지로 `connect` 사용해서 요청하면 됩니다

**Comment by ulgal** [comment]
혹시 디테일 페이지 내 여러 코멘트를 불러오는 이슈가 아직 해결이 안됐다면 아예 <Modal>을 ArticleDetail component에서 렌더링하지말고 BoardDetail에서 ArticleDetail을 부를 때
```
<Modal>
<ArticleDetail />
{comments}
</Modal>
```
이런 방식으로 변경하는 것도 괜찮을 것 같습니다.

**Comment by sungbin92** [comment]
수정해볼게요

**Comment by sungbin92** [comment]
article detail 내부에 comment 설치했습니다. hook 사용해서 설치했습니다. 아직 css랑 테스트 남았습니다.
