### ISSUE TITLE
[frontend] hot board

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#105]
hot board에 이상한 데이터들이 보이는 것 같습니다.
혹시 다른 분들 로컬에서도 핫 게시판에 추천수 10개 이하 게시글들이 보이나요?

**Comment by lightb0x** [comment]
`write-and-edit-card` 브랜치는 괜찮습니다

**Comment by ulgal** [comment]
DB 데이터 바꾼 뒤 확인하니 없어서 닫겠습니다.
