### ISSUE TITLE
[backend] DB가 또 안되네요

### ISSUE THREAD

**Issue by sungbin92** [swsnu/swpp2019-team19#110]
아까 user모델 바뀌기 전까지는 되다가 바뀐거 pull하고 나서 시작하니까 SNUBot DB에 account가 추가가 안됩니다.
처음부터 다시하기도 했는데도 그대로네요...

**Comment by sungbin92** [comment]
migration이 아예 안됩니다.
+------------------------+
| Tables_in_SNUBot       |
+------------------------+
| auth_group             |
| auth_group_permissions |
| auth_permission        |
| django_admin_log       |
| django_content_type    |
| django_migrations      |
| django_session         |
+------------------------+
몇번을 해도 저거밖에 테이블에 안들어가는데 이유를 모르겠네요

**Comment by ulgal** [comment]
conflict를 잘못 해결하신 것 같네요.
init.sh를 쓰지 말고 하나하나 쓰면서 에러메세지 확인해서 해보세요

**Comment by sungbin92** [comment]
해결했습니다
