### ISSUE TITLE
[shell script] update shell script

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#112]
백엔드에 `rasa` 가 추가되는 등의 이유로 셸 스크립트가 여러 곳에 흩어져있기도 하고, 제대로 업데이트가 되어있지 않습니다.

셸 스크립트 개선이 필요합니다. (파이썬으로 할 예정입니다)

카드 형식 write and edit 끝나면 시작하도록 하겠습니다.

**Comment by ulgal** [comment]
지금 SNUBot에만 쉘 스크립트가 있는 것 같고, 이 부분은 논의가 필요할 것 같습니다.

**Comment by ulgal** [comment]
shell script는 단순 db 초기화 시 이용하는 것 외에 사용하지 않는 것이 좋을 것 같아요. 이것도 서버에 올리고 난 뒤에는 초기 db를 잘 설정해서 shell script를 없애는게 좋을 것 같습니다.
그리고 스크립트의 개선이 필요하다는 부분은 이전에 이야기했던 md파일을 자동으로 만들어주는 것을 의미한다면 다른 방식으로 하는 것이 더 좋을 것 같습니다.

**Comment by lightb0x** [comment]
제가 의도한건 로컬에서 테스트하는 시점에 실행하는 스크립트를 말하는겁니다.
지금 백엔드가 하나가 아니라 둘이고, 따지고보면 프론트엔드에서도 패키지 설치하고 실행(`npm i && npm start`)해야 하므로 설치만 5분정도 걸려서 스크립트로 자동화하면 편하다고 생각했습니다

그리고 결국 서버에 올리더라도 설치를 쉽게 해주는 스크립트가 있으면 편합니다
최소 매일 업데이트할때마다 서버 내리고 정보 업데이트하고 다시 올리는식의 일을 일일이 수작업으로 하면 복잡해서 시간도 꽤 걸리고 실수할 확률도 생깁니다.

**Comment by ulgal** [comment]
현재 makefile을 로컬에서 arc를 이용해 요청을 보낼 것인지, 내부에서 python 스크립트를 짤 것인지, admin 페이지를 구현할 것인지 정해지지 않았습니다.

**Comment by ulgal** [comment]
python, shell script를 섞어서 api를 통해 제어
