### ISSUE TITLE
[frontend] navbar behavioral issue

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#121]
1. 사이드바 외의 위치를 클릭해도 사이드바가 사라지지 않습니다
2. 사이드바를 열고 검색창이나 아이디 입력칸 등을 클릭하면 사이드바 위로 최근 검색어/아이디가 나타납니다.

2번은 1번이 해결되면 자연스레 사라질것 같습니다

**Comment by ulgal** [comment]
1번은 Modal에서 단순 div로 바꿔서 그렇게 된 건데, 다시 Modal로 바꿔주면 됩니다. Modal 위에 디자인이 적용되는지 확인은 안해봤는데 적용 가능 할 거에요.

**Comment by ulgal** [comment]
Modal은 위치 문제가 있어 현재 상태로 가겠습니다.
