### ISSUE TITLE
Need resolve code smell

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#126]
SonarCloud가 code smell의 경우 fail로 간주하지 않아 pass했는데, 현재 component로 바꾸면서 중복된 이름 선언에 대한 code smell이 많아졌습니다.
정확히는 모르지만 코드를 보니 render 시 return 전에 확실히 mount되지 않는 상황 때문에 만든 것 같은데 이름을 바꾸거나 다른 방식으로 해결해야 할 것 같습니다.

**Comment by ulgal** [comment]
//const {
      //  username, newNickname, newEmail, currentPassword,
      //  newPassword, newPasswordConfirm,
      //} = this.state;
      const stateCopy = Object.xxx(this.state) // {...this.state}
      
      this.state.username
      stateCopy.username

**Comment by lightb0x** [comment]
PR [#136] 해결되었습니다
