### ISSUE TITLE
Custom user model deletion

### ISSUE THREAD

**Issue by desiderare** [swsnu/swpp2019-team19#131]
기존의 장고 유저 모델에서는 user.delete()가 작동하지만(이전 프로젝트 폴더에서 확인했습니다.), 현재 저희의 custom user model에서는 user.delete()가 작동하지 않습니다.

https://kite.com/blog/python/custom-django-user-model/

이 부분이 없어서 그런건지 확실히는 모르겠습니다.

Referencing the User model
If you’d like to support projects where the AUTH_USER_MODEL setting is modified, you unfortunately can’t just import the User model or reference it using appName.ModelName.

Django provides safe mechanisms for accessing the User model as needed.

Referencing the User model (without using the actual model class)

When you want to reference the User model without importing it, such as in defining foreign key relationships, you should use the AUTH_USER_MODEL setting:

 ## codes
from django.conf import settings
from django.db import models

class MyModel(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )

**Comment by ulgal** [comment]
shell에서 안된다는건가요?

**Comment by desiderare** [comment]
성민님 말대로 DB 리셋하니 다시 되는군요. 감사합니다.
