### ISSUE TITLE
[backend] sort on 'good' is not working

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#147]
백엔드 `/community/views.py` 의 `boards` 함수에서
`good` 에 대한 처리가 이상하고, 결론적으로 프론트엔드에서 제대로 작동하지 않습니다.

또한, `new` 나 `old` 에 대한 처리 또한 이상해보입니다.

**Comment by ulgal** [comment]
good은 확실히 잘못 동작하고 있는데, new와 old는 어떤 방식으로 이상한가요?

**Comment by lightb0x** [comment]
백엔드에서 처리할 때,
조건에 맞는 것들을 DB에서 가져오고 그 다음에 처리하는걸로 봐서
good에 대한 처리가 이상하듯 new 와 old 에 대한 처리도 이상하게 작동할거라 생각했습니다 (확인한건 아닙니다)

**Comment by ulgal** [comment]
굿을 제가 vote의 id순으로 정렬하게 잘못 짜놔서, diff로 바꾸면 정상동작하는데, old나 new는 제가 보기엔 정상적으로 작동하는 것 같습니다. 바꿔서 pr 올릴게요
