### ISSUE TITLE
[frontend?backend?] article edit bug

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#152]
`edit` 버튼을 누르면
수정하게 될 글의 내용이 기본으로 들어가있는 `edit`창이 나타나게 되는데,
그 기본 내용이 잘못되어있는 문제입니다.
다른 글의 내용을 기본 내용으로 가져오는 경우가 있습니다.

**Comment by ulgal** [comment]
Frontend의 ArticleCreate component에서 return 직전에
```js
if (articleTitle === '' && articleTitle !== title) {
    setTitle(title);
  }
if (articleContent === '' && articleContent !== content) {
  setContent(content);
}
```
부분이 문제인 것 같습니다. 
Javascript에서 Modal은 누를 때 렌더링되는 것이 아니라 페이지가 로드될 때 렌더링 됩니다. 따라서 6개의 ```ArticleEntry```가 모두 내부의 Modal까지 렌더링은 되어 있지만, 누르기 전까지는 ```ArticleEntry```에서 storedArticle이 없기 때문에 props를 전달하지 않아 아무 것도 없는 상태입니다.
여기서 처음 Article을 클릭하면 store에 Article이 저장되고, 이를 모든 ```ArticleEntry```에서 각자의 ```ArticleDetail```에 props로 넘겨주고 다시 ```ArticleCreate```에 넘겨줘 const인 articleContent가 선언됩니다. 이후 다른 Article을 클릭해서 Edit하려고 하면 페이지가 렌더링 된 이후 가장 먼저 저장된 article의 title과 content가 ```articleTitle```, ```articleContent```에 남아있고, if문의 &&을 충족하지 못해서 ```setTitle```과 ```setContent```가 안불리고 return하게 됩니다. 그래서 바꾸면 해당하는 article이 바뀌는데(article.id를 받고, const 같은 방식으로 id를 따로 처리하지 않음), Title과 Content가 잘못 표시되는 현상이 생겼습니다. 근데 이 부분이 create하는 부분과도 관련된 것 같아서 단순히 ```&& -> ||```로 바꾸거나 ```articleTitle === ''``` 조건을 빼면 동작하지 않아서, 동작 방식을 수정해야 할 수도 있을 것 같습니다.

**Comment by ulgal** [comment]
이 부분은 고쳐보려 해도 다른 것들과 dependency가 있는 것 같아서 명환님이 해주시면 좋을 것 같습니다.

**Comment by lightb0x** [comment]
resolved in #153
