### ISSUE TITLE
[refactoring] duplicate items

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#16]
수업시간에 나온 HW2의 `create`와 `edit`처럼, 프로젝트에서도 `component` 로 나눠야 할 필요성이 있습니다.

또, 보드가 여러개지만 다른 건 거의 없으므로 이것도 `component` 로 분리하면 좋을 것 같습니다.

**Comment by desiderare** [comment]
HOC 말씀하시는건가요?

**Comment by lightb0x** [comment]
58페이지에 나오는걸 보고 쓴건데요, 구체적으로 HOC가 될지 단순 `component`가 될지는 생각해봐야겠네요.

**Comment by ulgal** [comment]
어느 정도 컴포넌트화 되었으니 닫겠습니다.
