### ISSUE TITLE
[alpha testing] guidelines

### ISSUE THREAD

**Issue by dkim94** [swsnu/swpp2019-team19#167]
입력할 수 있는 질문에 대한 가이드라인이 있으면 더 좋을 것 같아요!
자칫하면 엉뚱한 대답만 내놓는다는 평을 들을 수도 있을 것 같아서요 ㅠㅠ

**Comment by ulgal** [comment]
반영해서 UI를 개선하도록 하겠습니다. 좋은 의견 감사합니다.

**Comment by lightb0x** [comment]
moved to #176
