### ISSUE TITLE
[alpha testing]

### ISSUE THREAD

**Issue by gywls00** [swsnu/swpp2019-team19#172]
같은 질문인데 여러 형태로 하면 못알아듣는게 많은 것 같습니다
예를들어 i'm hungry 하면 식단을 알려주는데
what is today's menu? 하면 대답을 하지 못합니다.

**Comment by ulgal** [comment]
이 부분은 현재 기본적으로 제공되는 set에 몇 개만 단순하게 추가해서 생기는 오류여서, 추후 모델 추가 시 해결될 것 같습니다. 감사합니다.
