### ISSUE TITLE
[alpha testing] sign in 400 error

### ISSUE THREAD

**Issue by coffeetea99** [swsnu/swpp2019-team19#173]
signup에서 400에러가 뜹니다. input에 조건이 있는 것 같은데 명시되지 않아 잘 모르겠습니다.
그리고 400이 떴는데도 sign in 페이지로 돌아오니 마치 가입이 된 것 같아 혼란을 줄 수 있을 것 같습니다.
(그리고 Uername or Password is wrong 이라는 오타가 있습니다)

**Comment by lightb0x** [comment]
#174 로 옮겼습니다. 해결하도록 하겠습니다 감사합니다!
