### ISSUE TITLE
[frontend] signup error

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#174]
장고 유저 모델을 커스텀 모델로 바꾸면서, 프론트엔드에 닉네임을 추가하지 않아서 생긴 문제입니다.
닉네임 필드를 만들고, action에 nickname을 같이 보내면 될 것 같습니다.
더불어 400 에러에 대한 표시가 없어서, 400 status를 반환받을 떄에 대한 state를 reducer에 추가하면 될 것 같습니다.

**Comment by lightb0x** [comment]
signup시 400 에러가 발생합니다.

#173 
#169 
#168 
#166

**Comment by ulgal** [comment]
서버에 반영했습니다.
