### ISSUE TITLE
[frontend & backend] categorize question set

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#176]
alpha test에서 어떤 질문들에 대해 답할 수 있는지에 대한 문의가 많았습니다. 현재 django model에 있는 story 네임들을 가공해서 질문할 수 있는 category 형식으로 보여주면 좋을 것 같습니다.
category는 채팅창 화면 옆에 둬야 할 것 같아서, UI를 전체적으로 수정해야 할 것 같습니다.

**Comment by ulgal** [comment]
#167 #170 #171

**Comment by lightb0x** [comment]
`about` 페이지에 넣는건 어떨까요?

**Comment by ulgal** [comment]
about 페이지에 넣는거보단 [link](https://react-bootstrap.github.io/components/overlays/#popovers)를 이용해서 topbar에 넣는게 좋을 것 같아요.
목록을 어떻게 받아오는지가 중요한데, api 만들어놓은 것 중에 story와 intent 부분만 추려서 보내주는게 좋을 것같아요.
