### ISSUE TITLE
[Rasa, Frontend] sender

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#189]
Rasa api는 sender와 message field가 필요한데, sender를 통해 story 정보를 보관하기 때문에, 현재처럼 default로 보내는 방식은 다른 유저의 스토리가 섞일 수 있습니다.
해결 방안으로는
1. story를 단순히 하나로만 제한
2. sender를 login한 경우 username, 아닌 경우 n자리(6~10)의 random string으로 할당

2번의 방식으로 구현하는 것이 더 좋을 것 같습니다.

**Comment by lightb0x** [comment]
merged to master #198 
CSRF token 중 마지막 20자리 글자를 사용합니다.
