### ISSUE TITLE
[refactoring] no more alert!

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#19]
`SonarCloud`에서 `alert` 를 사용하지 말도록 추천하고 있기 때문에, `alert` 들을 모두 바꿔야 합니다.

예시) 
[네이버](https://nid.naver.com/nidlogin.login?mode=form&url=https%3A%2F%2Fwww.naver.com)
[다음](https://logins.daum.net/accounts/signinform.do?url=https%3A%2F%2Fwww.daum.net%2F)

다음 예시를 따라가는 게 좋을것같습니다

**Comment by lightb0x** [comment]
Merged to master

**Comment by ulgal** [comment]
user action의 signin에 남아있습니다.

**Comment by lightb0x** [comment]
이제 `alert` 대신 `Alert`를 사용합니다. (7379169)
