### ISSUE TITLE
[last sprint] todo

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#216]
### frontend
- 전체적인 버튼모양과 색깔, 테마 색깔 결정

- fallback 대답이 나올 때 board 로 넘어가는 옵션 제공 (모르겠어요 -> 알려주세요)

- admin page (superuser-only, for model update)

- about page 구현

- 챗봇이 지원하는 질문 목록들 (가이드, 튜토리얼 같은 느낌)

- documentation update (화요일까지)

**Comment by ulgal** [comment]
fallback 대답의 경우 적절한 string을 주시면 추가하는건 어렵지 않습니다.
admin page는 priority는 낮은 편이고, 구현은 어렵지 않을 것 같아요. 이미 서버 nginx 세팅에 /api 이외에 /rasa_eng, /rasa_kor도 8000번으로 가게 했기 때문에 똑같이 구현하고, action에서 axios만 /api가 아니라 /rasa_eng로 시작하면 됩니다.
about page는 따로 구현하기보다  [popover](https://react-bootstrap.github.io/components/overlays/#popovers)를 사용해서 간단히 보여주는게 좋을 것 같아요. 이를 위해서 story와 해당하는 intent의 첫번째 토큰을 예시로 보내주는 api를 만들게요.
질문 목록들은 위처럼 합치면 될 것 같아요.

**Comment by ulgal** [comment]
### 남은 기간에 추가하면 좋을 feature
- Guide(Tutorial)
- UI
- admin page

**Comment by ulgal** [comment]
일단 Guide(Tutorial) 부분은 제가 api랑 프론트 popover 이용해서 만들어볼게요

**Comment by lightb0x** [comment]
admin page 만들어볼게요

**Comment by lightb0x** [comment]
챗페이지 UI 작업하고있습니다
(챗페이지 높이가 한 페이지 넘어가는 문제)

**Comment by lightb0x** [comment]
챗페이지 UI는 끝났고, 버튼 색깔 바꾸는 방법을 찾아볼게요

**Comment by ulgal** [comment]
mobile sidebar UI

**Comment by ulgal** [comment]
> 챗페이지 UI는 끝났고, 버튼 색깔 바꾸는 방법을 찾아볼게요

모바일에서 signin, signup, account 등의 페이지도 위에 공간이 뜨는데 이 부분도 비슷한 방법으로 해결할 수 있을 것 같아요.

**Comment by ulgal** [comment]
모바일 테스트는 크롬 개발자모드에서 360/640으로 하면 됩니다.

**Comment by ulgal** [comment]
topbar 색은 스누블루로 할게요

**Comment by lightb0x** [comment]
아뇨 지금 몇개 해보고있어요

**Comment by lightb0x** [comment]
처음에는 [이 색배합](https://www.color-hex.com/color-palette/85918)으로 해봤고
<img width="687" alt="theme1" src="https://user-images.githubusercontent.com/17784659/70850031-5dd94000-1ec9-11ea-97ea-a0cb79fcff1c.png">
지금은 [이 색배합](https://www.color-hex.com/color-palette/85527)으로 해보고있습니다

**Comment by ulgal** [comment]
저희 포스터, 로고를 생각했을 때 탑바는 스누블루로 고정하고 사이드바와 배경색을 바꾸는 방식을 하는게 좋지 않을까요?

**Comment by ulgal** [comment]
위에 색배합 보니 좋은 것 같네요.
일단 그럼 색상은 제외하고 크기조절만 PR날릴게요

**Comment by ulgal** [comment]
버튼들이 지금 signin, signup등으로 하면 버튼의 배경색에 다 지워지는데, 로고 만들듯이 이미지로 만들어서(Sign Up 이미지) 올리면 쉽게 해결할 수 있으면서 크기 조절도 잘 됩니다. 대부분의 버튼들은 이렇게 이미지같은걸로 대체하는게 좋을 것 같아요.

**Comment by lightb0x** [comment]
두번째 색배합 해보고 있는데 둘 중 어떤게 더 낫나요??
<img width="687" alt="스크린샷 2019-12-14 오후 11 47 30" src="https://user-images.githubusercontent.com/17784659/70850313-30da5c80-1ecc-11ea-864a-433406c73f63.png">

**Comment by ulgal** [comment]
두번째가 더 나은 것 같아요

**Comment by lightb0x** [comment]
카드 배경색만 바꿨더니 글자가 하예서 안보이는 색깔들이 있네요
이 문제하고 signin 페이지 높이조절할게요

**Comment by lightb0x** [comment]
그리고 챗페이지에서 가이드 표시가 안되는거같네요

**Comment by ulgal** [comment]
챗페이지에 가이드는 표시됩니다.
![image](https://user-images.githubusercontent.com/48579185/70850844-1905d700-1ed2-11ea-973d-54f200ca873d.png)

**Comment by ulgal** [comment]
현재 모바일/HD환경에서 스크롤 기능 구현했습니다.
>HD와 태블릿의 경우 고려하지 않도록 하겠습니다.

**Comment by ulgal** [comment]
model update, model refresh api 구현했습니다.
admin 계정으로 들어가서 accountinformation들어가면 나오게 해놨습니다.
새로고침한 경우 다시 로그인해야합니다.

**Comment by lightb0x** [comment]
글자색, 카드크기 조절 완료
