### ISSUE TITLE
[frontend] accountinfo change bug

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#238]
계정정보 변경할 때, 기존 비밀번호가 다르면 submit 시에 페이지에 navbar 제외하고 아무것도 표시되지 않습니다

**Comment by ulgal** [comment]
이거 수정해서 올리실 때 short guide 부분에
정확한 단어를 검색해야 한다는 뉘앙스로 영문/한글 추가해주실수 있나요?
You have to ask the exact word 같은느낌으로

**Comment by lightb0x** [comment]
merged to master #240
