### ISSUE TITLE
[Documentation] final documentation

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#258]
각자 파트 알려주세요

**Comment by ulgal** [comment]
System Architecture, Controller, Design Details - Backend, Implementation plan, Testing plan

**Comment by lightb0x** [comment]
Design Details - Frontend - (Organization - Containers), Relations, (algorithms - containers)

**Comment by sungbin92** [comment]
Design Details - Frontend - (Organization - Redux), Relations (react container - redux)

**Comment by desiderare** [comment]
ERDiagram, Relation schema based on ER relationship, Design Details - Algorithms

**Comment by lightb0x** [comment]
제가 맡은 부분은 끝났습니다.
