### ISSUE TITLE
[frontend behavior bug] always redirect to `/all`

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#54]
`communityMain` 에서 게시글을 클릭해 들어가면 항상 `/all` 게시판으로만 들어가집니다.

게시글에 따라 `/all` 또는 `/hot` 으로 들어가도록 바뀌어야 합니다.

**Comment by ulgal** [comment]
게시글을 modal형식으로 보도록 바뀌어서 해결되었습니다
