### ISSUE TITLE
[frontend] like & dislike button behavioral issue

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#55]
지금은 로그인되지 않은 상태에서 버튼을 누르면 아무 일도 일어나지 않습니다.

로그인되지 않은 상태라면 클릭시 로그인이 필요하다는 알림을 띄우거나 버튼을 `disable` 하는 식의 수정이 필요해보입니다.

**Comment by lightb0x** [comment]
지금의 행동은 다음과 같습니다:

like 버튼을 누른 후 dislike 버튼을 누르면 like 의 숫자가 줄어듭니다

여기에서 -> 다음으로 바뀌면 좋을 것 같습니다

like 버튼을 누른 후 다시 like 버튼을 누르는 경우 like 의 숫자가 줄어듭니다.
like버튼과 dislike버튼의 행동이 분리되어야 합니다.

**Comment by desiderare** [comment]
> 지금의 행동은 다음과 같습니다:
> 
> like 버튼을 누른 후 dislike 버튼을 누르면 like 의 숫자가 줄어듭니다
> 
> 여기에서 -> 다음으로 바뀌면 좋을 것 같습니다
> 
> like 버튼을 누른 후 다시 like 버튼을 누르는 경우 like 의 숫자가 줄어듭니다.
> like버튼과 dislike버튼의 행동이 분리되어야 합니다.

 이렇게 바꾸려면 Vote UI 체계를 쫌 바꿔야될 것 같습니다.

**Comment by lightb0x** [comment]
추천버튼 두번 클릭시 추천이 취소되도록 변경되었습니다 PR #137 
로그인되어있지 않을 때 적절한 행동이 필요합니다 (버튼 `disable` 처리, 또는 알림 `Modal` 띄우기 등)

**Comment by lightb0x** [comment]
PR #149 
중
e9e2858
에서 해결
