### ISSUE TITLE
testing history is not available [#64]

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#65]
#64 에서, 테스트를 작성하기가 불가능해보입니다.

하나의 테스트에서는 `create` 로 가고, 다른 테스트에서는 `board`로 가야 하는데, `history`가 `mock`이 안되었는지 테스트가 불가능합니다.

이를 해결하기 위해선 테스트 양식 (템플릿)을 바꿔야 합니다.

**Comment by ulgal** [comment]
board로 가는걸 체크하는게 아니라 board로 가는 버튼이 눌린걸 체크하는 방식 아니였나요?
모든 테스트에서 url체크는 하지 않았던걸로 기억합니다.

**Comment by lightb0x** [comment]
URL 넘어가는걸 확인해야 제대로 된 테스트라고 생각합니다.
이와 별개로, `history`를 `afterEach`에서 리셋해서 이제는 테스트가 제대로 돌긴 합니다.
