### ISSUE TITLE
[frontend & backend?] missing good tests

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#75]
코드가 많이 추가되었지만 테스트는 그만큼 추가되지 않아 커버리지가 떨어지고있습니다.

특히, `Branch` 커버리지는 이미 80% 이하로 떨어졌습니다.

난관은 다음과 같습니다:
1. dropdown 선택하기
2. `action`, `reducer` 테스트
등등

**Comment by ulgal** [comment]
일단 커버리지가 떨어진 부분은 어느 정도 해결했습니다. 캐시된 이미지라 반영이 안되고 있지만 93%정도이고, BoardDetail, CommunityMain의 여러 기능들을 테스트하면 좀 더 올라갈 것 같습니다.

**Comment by lightb0x** [comment]
now coverage over 90%
