### ISSUE TITLE
[RASA] while install

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#76]
`rasa`를 설치하면 도중에 `tensorflow`를 설치하는데, `tensorflow`는 파이썬 `3.5.x`, `3.6.x` 만 지원합니다.

따라서, `pyenv` 등을 통해 파이썬 버전을 위와 같이 바꾸고 설치하셔야 합니다.

**Comment by ulgal** [comment]
description에 반영됐습니다.
