### ISSUE TITLE
[rasa] backend configuration

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#77]
지금은 데모를 위해 빠르게 준비하느라 `django` 백엔드 서버와 `rasa` 백엔드 서버가 완전히 분리되어있으며 유저 정보는 `default`라는 스트링으로 들어가게 됩니다.

당장 세션 하나로 동작하는데는 문제가 없겠지만 이후에 여러명이 동시에 접속하는 상황을 상정하면 문제가 생길수도 있을것같고, 더 나은 백엔드 구성을 위해서도 `frontend` - `django` - `rasa` 이런식으로 연결하는게 좋을것같습니다.

이렇게 하면 사용자가 장고로 요청을 보내면(챗을 남기면) 장고에서 사용자의 `sessionid`를 사용해 `rasa`에 넘길 수 있습니다. 즉, 간결하고 편리합니다.

더 나은 백엔드 구성이 의미하는것은, 추후에 `rasa` 부하가 커지게 되면 이를 여러 서버로 분할할 수도 있어야 할텐데, 이 때 장고 백엔드 서버에서 사용자들을 여러 `rasa` 서버로 분산시키는(뿌려주는) 것을 말합니다.

**Comment by ulgal** [comment]
기존 rasa의 스토리가 한 포트로 하나의 요청이 들어오면 그 스토리 상태를 저장하고 있는 것 같은데, 유저 정보에 따라 스토리를 저장하는지 확인해봐야 할 것 같습니다. load balancing 시 한 유저가 어느 서버로 요청을 보냈는지를 저장하고 있어야 스토리 기능을 활용할 수 있을 것 같습니다.

**Comment by ulgal** [comment]
독립적으로 구성해서 deploy했습니다.
