### ISSUE TITLE
[rasa] automating information configuration

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#80]
`rasa`에는 세 가지 파일들을 저희가 고칠 수 있습니다: `stories.md`, `nlu.md`, `domain.yml`.

story 안에 story를 넣는게 힘든거같아서, 이를 빠르고 쉽게 만들 수 있는 코드 (아마 파이썬)를 만든다면 좋을 것 같습니다.

[여기](https://rasa.com/docs/rasa/core/stories/)에서 `checkpoint`에 대해 얘기하고는 있으나 권장하는 방식이 아니라서 직접 스크립트를 만드는 게 더 좋을 것 같습니다.

**Comment by ulgal** [comment]
#83 dup
