### ISSUE TITLE
[rasa challenge] 한국어 지원

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#82]
한국어 지원을 통해 양질의 답을 얻을 수 있으면 좋을 것 같습니다.

만약 챗봇에서 한국어 지원이 되면 홈페이지 전체적으로 한국어/영어 선택할 수 있는 메뉴, 그리고 그에 따른 한글화 작업도 필요합니다.

**Comment by lightb0x** [comment]
한글에 대한 `entity extractor`가 필요합니다.
가능한 해결책은 다음 중 하나가 될 수 있습니다:

1. `rasa` 한글 `entity extractor`를 찾아서 적용하기
2. `rasa` 한글 `entity extractor`를 직접 만들기
3. `rasa`와 `django` 서버 사이에 처리장치(`ChatterBot`, `KoNLPy` 등)를 둬서 `rasa`에 들어가기 전 전처리과정 거치기

3번의 경우 `rasa` 서버 연결을 `django`서버를 통해 연결하는 것으로 바꿀 필요가 있습니다.

**Comment by ulgal** [comment]
한국어 pipeline은 supervised_embedding과 비슷하게 하고
whitespacetokenizer만 형태소분석기로 대체하였습니다.
