### ISSUE TITLE
[frontend] UI

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#84]
기능 구현만 해서 보기 흉합니다.
적절한 UI를 생각해보고 템플릿을 찾아보거나 부트스트랩 활용해서 만들어봅시다

**Comment by lightb0x** [comment]
`CommunityMain`, `BoardDetail`, `ArticleDetail` 모두 카드 형식으로 만들도록 했습니다.

**Comment by lightb0x** [comment]
[부트스트랩 카드](https://react-bootstrap.github.io/components/cards/)

**Comment by lightb0x** [comment]
`status` 따라서 색깔 입히는 것도 쉽게 할 수 있습니다.

**Comment by lightb0x** [comment]
#74 에서 `pagination` 을 만들도록 했었는데, 카드 슬라이드오버 형식과 `pagination`이 서로 모순되는 것 같습니다. 구체적으로 정할 필요가 있습니다.

**Comment by ulgal** [comment]
pagination을 살리기로 했습니다. 다른 파트들도 적절히 UI가 적용되었기 때문에 닫겠습니다.
