### ISSUE TITLE
[frontend] generate key for component

### ISSUE THREAD

**Issue by ulgal** [swsnu/swpp2019-team19#85]
현재 각 message component에 key를 uuid4라는 방식에서 단순히 bitwise를 module로 변형해서 key를 만들고 있는데, local에선 문제 없지만 여러 유저가 사용한다고 가정 시 좋지 못한 알고리즘이기도 하고, sonarcloud의 security hotspot에 Math.random()을 generator로 사용할 시 주의하라는 message가 뜹니다. 
만든 숫자가 단순히 중복을 피하기 위한 용도로 쓰일 뿐 다른 용도로는 쓰이지 않아 secure할 필요는 없지만 뭔가 좋은 방법이 있으면 그 방식으로 바꾸는게 좋을 것 같습니다.

**Comment by lightb0x** [comment]
`UUID4` 방식을 사용하는 게 바람직하지 않긴 하지만 굳이 바꿀 필요가 없기도 합니다.

**Comment by lightb0x** [comment]
단순 카운터 형식으로 변경했습니다 PR #137
