### ISSUE TITLE
[frontend] [wechat-theme] styling error

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#90]
챗이 위에서 아래로 진행되어야 하는데,
지금은 왼쪽에서 오른쪽으로 진행되고
말풍선이 위아래로 긴 문제가 있습니다.

**Comment by lightb0x** [comment]
[소스](https://www.bootdey.com/snippets/view/Whatsapp-web-chat-template#preview)

**Comment by ulgal** [comment]
#99
