### ISSUE TITLE
[frontend] coloring

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#91]
색깔 정하기

1. 헤더 (`navbar`)색깔 정하기
2. 전체 테마(`background`) 색깔 정하기

**Comment by lightb0x** [comment]
# named colors
whatsapp bubble: #dcf8c6

imessage blue : #0066FF

ios colors
#5fc9f8
#fecb2e
#fd9426
#fc3158
#147efb
#53d769
#fc3d39
#8e8e93

[Pantone® Color of the Year](https://codepen.io/cassiocardoso/details/JbBgxP)
2019: #ff6f61
2018: #5f4b8b
2017: #88b04b
2016: #f7cac9, #8ca4cf

vscode `*.css` 파일에 넣으면 바로 색깔로 표시됩니다.
아무거나 생각나는대로 색깔 추가해주세요

**Comment by lightb0x** [comment]
[여기](https://favicon.io/favicon-generator/)에서 favicon을 만들 수 있습니다.

**Comment by lightb0x** [comment]
[여기](https://logohub.io)에서 로고를 만들 수 있습니다.

**Comment by ulgal** [comment]
#223
