### ISSUE TITLE
[backend] mySQL settings issue & solutions

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#97]
mySQL 설정하는 중에 오류가 생겨서 해결책을 남겨둡니다.

1. `mysqlclient 1.3.13 or newer is required; you have 0.9.3`
위와 비슷한 파일 경로(`/mysql`)를 따라가서 `base.py`를 다음과 같이 편집
```python
if version < (1, 3, 13):
   pass
   '''
   raise ImproperlyConfigured(
       'mysqlclient 1.3.13 or newer is required; you have %s.'
       % Database.__version__
   )
   '''
```
그리고 `mysql/operations.py`에서 `query = query.decode(errors='replace')` 를 `query = query.encode(errors='replace')`로 대체
관련 [링크](https://stackoverflow.com/questions/55657752/django-installing-mysqlclient-error-mysqlclient-1-3-13-or-newer-is-required)

(1번에서 decode 를 encode로 바꿨으면 문제가 발생하지 않을 확률이 높음)
2. `AttributeError: 'str' object has no attribute 'decode'`
`trace`에 나오는 파일(대략 `django/db/backends/mysql/operations.py`)에서
`query = query.encode(errors='replace')`를 찾아서 `query = errors='replace'`로 대체
관련 [링크](https://stackoverflow.com/questions/56820895/migrations-error-in-django-2-attributeerror-str-object-has-no-attribute-dec)

**Comment by ulgal** [comment]
로컬에서 설치된 패키지의 내용을 바꿔야 동작하는건 문제가 있는 것 같은데요.
```
mysqlclient==1.4.5
pymysql==0.9.3
```
mysqlclient가 pymysql에서 나온건데 두개가 같이 있으니 pymysql을 인식해서 버전이 안맞다고 하는 것 같아요. pymysql을 안쓰고 사용하는 방법을 찾아보는게 좋을 것 같습니다.

**Comment by lightb0x** [comment]
맥에선 같은 코드로 설정이 불가능합니다.
따라서 로컬에서 수동으로 설정해서 사용해야 합니다.

DB를 클라우드에 올려서 써도 됩니다. (결국엔 이렇게 써야겠죠?)

**Comment by ulgal** [comment]
db가 아니라 프로젝트 전체를 azure에 올려서 사용할 예정입니다. 지금 로컬은 그냥 작은 사이즈에서 테스트용이죠.

**Comment by lightb0x** [comment]
DB를 azure 서버에 올릴때까지 유지하겠습니다.

**Comment by lightb0x** [comment]
`DB.md` 로 합치고 닫겠습니다
