### ISSUE TITLE
[frontend] display using Card

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team19#98]
게시글들이 표시되는 형식을 `card` 형식으로 바꿔야 합니다.

1. `CommunityMain` 페이지 변경
2. `BoardDetail` 페이지 변경
3. `ArticleDetail` 페이지 변경 또는 삭제 (`Modal` Component 형식으로 변경)

**Comment by desiderare** [comment]
아직 ArticleDetail에 로그인되지 않은 상황에서 signin이나 signup으로 넘어가는 기능을 Modal 테스트 커버리지가 부족해서 풀리퀴스트를 보내지 않았습니다. 어차피 ArticleDetail에 큰 변화가 있다면 테스트 커버리지 조금 부족해도 풀리퀘스트를 보낼까요?

**Comment by ulgal** [comment]
ArticleDetail에 큰 변화가 있다면 굳이 커버리지를 낮추는 풀리퀘스트를 할 필요는 없다고 생각합니다.

**Comment by desiderare** [comment]
UI 변화주실 때 로그인되지 않았을 경우 투표기능이 없어서 귀찮으실 것 같아서요. 필요 없으시면 그냥 두고 필요하시면 아티클 디테일 기능 추가된 JS 파일 보내 드리겠습니다.

**Comment by ulgal** [comment]
이미 한 부분이 있으면 브랜치 파서 풀리퀘스트 넣어주세요

**Comment by lightb0x** [comment]
지금 어느부분까지 진행이 된거죠?

**Comment by desiderare** [comment]
로그인 상태확인하고 안되어 있으면 모달 써서 로그인이나 사인업 페이지로 갈 수 있는 상태는 구현 해놓았고, 마스터에 올라간 코드는 로그인 안했으면 투표해도 숫자변동이 없는 상태입니다.

**Comment by lightb0x** [comment]
UI 구현이 어느정도 됐는지가 궁금합니다.
지금 하고있어서요 이미 된거면 다른거 하려구요

**Comment by desiderare** [comment]
저도 다른거 하느라 UI는 구현은 안했습니다. 저번 발표 직전 보신 기능 말한겁니다. 그럼 그냥 나두겠습니다!!

**Comment by lightb0x** [comment]
merge to master (#101)
